<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ujamii_dsgvo"
 *
 * Auto generated by Extension Builder 2018-04-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'DSGVO Compliance',
    'description' => '',
    'category' => 'module',
    'author' => 'Michael Grundkötter',
    'author_email' => 'mg@ujamii.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
